version: '3'

services:
  db:
    image: postgres:16
    # ports:
    #   - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7.2.4
    # ports:
    #   - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis/data

  api:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

    volumes:
      - .:/app
    expose:
      - 3000
    depends_on:
      - db
      - redis
    # environment:
      # DB_HOST: db
    env_file:
      - ./.env

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
