FROM ruby:3.2.7

WORKDIR /app
COPY Gemfile ./
COPY Gemfile.lock ./
RUN bundle config set --local deployment true
RUN bundle install -j $(nproc)
RUN bundle lock --add-platform arm64-darwin-22
RUN bundle lock --add-platform aarch64-linux
RUN bundle lock --add-platform x86_64-linux
COPY . .
# RUN chmod +x ./entrypoint.sh
# ENTRYPOINT ["./entrypoint.sh"]
# RUN rails db:migrate
RUN rails assets:precompile
CMD ["rails", "s", "-p", "3000", "-b", "0.0.0.0"]
