version: '3'

services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'usertest'
      POSTGRES_PASSWORD: 'password123123'
      POSTGRES_DB: 'test_database'

  redis:
    image: redis:7.2.4
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      RAILS_ENV: test
      DATABASE_URL: 'postgresql://usertest:password123123@db:5432/test_database'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
