version: '3'

services:
  db:
    image: postgres:16
    # ports:
    #   - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # load above envs from secrets github ?????

  redis:
    image: redis:7.2.4
    # ports:
    #   - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis/data

  api:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    volumes:
      - .:/app
      - nginx_conf_volume:/app/default.conf
      - public_html_volume:/app/public
    expose:
      - 3000
    depends_on:
      - db
      - redis
    # environment:
      # DB_HOST: db

  sidekiq:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - nginx_conf_volume:/etc/nginx/conf.d/${DOMAIN_NAME}.conf # double-check
      - public_html_volume:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # # ci: copy from domain.conf.template, build -> image, run image -> api
      # # this volumn should be shared with api

      # - ./public:/usr/share/nginx/html 
      # # this volumn should be shared with api

      - /etc/letsencrypt:/etc/letsencrypt
      # server should prepare ssl
    ports:
      - 443:443
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
  nginx_conf_volume:
  public_html_volume:
