name: 'Run Test Development'
description: 'Test Development Job'

runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Cache Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundle-

    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install -j $(nproc) --retry 3

    # - run:  bin/rails db:schema:load

    - name: Lint Ruby files
      run: bundle exec rubocop --parallel

    - name: Check security vulnerabilities(brakeman)
      run: bundle exec brakeman

    - name: Check security vulnerabilities(bundle-audit)
      run: bundle exec bundle-audit check --update

    - name: Run tests
      run: bundle exec rspec
