name: CI Development COPY 1

on:
  pull_request:
    branches:
    - develop

    types: [opened, synchronize, reopened]


jobs:
  run_test_Development:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop')
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: test_database
          POSTGRES_USER: usertest
          POSTGRES_PASSWORD: password123123
        options: >-
          --health-cmd "pg_isready -U usertest -d test_database -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgresql://usertest:password123123@localhost:5432/test_database'
      RAILS_MASTER_KEY: 'd4f6d3124335ac721ff0c10b93ec2cb0'
      POSTGRES_HOST: db
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: password123123
      POSTGRES_DB: test_database
      REDIS_URL: redis://redis:6379/0
      YOUTUBE_API_KEY: ''

    steps:
      - name: Run Test Development
        uses: ./.github/actions/run_test_Development


  need_merge_develop_approval:
    runs-on: ubuntu-latest
    environment:
      name: approval_merge_develop_branch
    steps:
      - name: Wait for merge approval 
        run: echo "Waiting for admin merge approval..."
